### ISSUE TITLE
Tasks Sync

### ISSUE THREAD

**Issue by spekulatius** [pcsg/pcsg-makerlog-php-client#4]
Hey @dehenne 

do you plan to implement the task sync endpoint (tasks since a provided date)? Just asking as it could come in handy in a current project im working on.

-- Peter

**Comment by dehenne** [comment]
Yeah, definitely.  Until two or three weeks ago, the API just wasn't so stable.

**Comment by spekulatius** [comment]
yeah, thats fair enough. Do you actually know if you can filter tasks by
user using the API?

**Comment by dehenne** [comment]
@spekulatius i implemented the sync method for you. but it could that the api changes a bit in the future. i haven't quite understood what the sync should be good for yet. :thinking: can you explain it?

**Comment by dehenne** [comment]
oh, btw, i implemented the Task API. At least 90% of it.
https://github.com/pcsg/pcsg-makerlog-php-client/blob/master/docs/tasks.md

**Comment by spekulatius** [comment]
Awesome! Thank you so much @dehenne!

**Comment by spekulatius** [comment]
Ups. Closed it accidentally. Sync is probably not the best word - it's an option to filter by a "since date". Does this make sense?

**Comment by dehenne** [comment]
🤔 has this Method parameter? If so, than i have to implement it.

**Comment by spekulatius** [comment]
yeah, there should be a date you can hand over. Can't remember the name
atm. Check the playground - I'm sure you will find it there.

**Comment by dehenne** [comment]
Ok. @spekulatius the parameters are implemented ;-)

**Comment by spekulatius** [comment]
Awesome. Thanks Henning!
