### ISSUE TITLE
Search endpoint

### ISSUE THREAD

**Issue by spekulatius** [pcsg/pcsg-makerlog-php-client#6]
Hello Henning,

I've just had a chat with Sergio around how to find certain tasks using the makerlog API. He pointed me to an (undocumented?) endpoint I should use: search :smile: (e.g. https://api.getmakerlog.com/search/tasks/?q=makerlog )  

Do you think this is something you would like to have added in? For now the task search is the most interesting one I would think. I promise it will be the last time I annoy you as I should be able to build my project using your lib from there on :wink: 

Let me know what you think.

-- Peter

@dehenne

**Comment by dehenne** [comment]
:scream: sure! I will add it ... I will try to implement it tmr :+1: . I hope I'm not forgetting that.

**Comment by spekulatius** [comment]
Yay, this is becoming a great library! 😍

**Comment by dehenne** [comment]
ok I've implemented this quickly, so you can use it ;-) but I want to have a look at the API later.

```php
$Tasks  = $Makerlog->getTasks();
$result = $Tasks->search('test');
```

result

```
class stdClass#17 (4) {
  public $count =>
  int(0)
  public $next =>
  NULL
  public $previous =>
  NULL
  public $results =>
  array(0) {
  }
}
```

since you can specify limits and pages here, the api has to be extended, anyway it looks to me that way. :-)

**Comment by spekulatius** [comment]
Great, thank you 🙏️ I'll keep you posted how it goes!

**Comment by spekulatius** [comment]
Hey @dehenne 

I've tried this and it seems like I'm getting no results. In detail I've tried:

- search term "productsync" (which has results: https://api.getmakerlog.com/search/tasks/?q=productsync )
- with and without token.
- with and without debug flag

The code I've used is fairly simple: 

        $makerlog = new \PCSG\Makerlog\Makerlog([
            'access_token' => $makerlog_token,
            'debug' => false,
        ]);

        $result = $makerlog->getTasks()->search('productsync');

        var_dump($result);die;

Token and debug flag are options I've tried while debugging it.

Any idea what the reason is? Do you think you could have a look and see if it works for you?

Cheers,
Peter

**Comment by dehenne** [comment]
hey @spekulatius,  I'll check it out tomorrow. ;-)

**Comment by spekulatius** [comment]
Cool, thank you 👍

**Comment by dehenne** [comment]
ok, its fixed ;-)

**Comment by dehenne** [comment]
can you find out which parameters are still available? Sergio should know more :laughing:

**Comment by spekulatius** [comment]
Thank you Henning! I'll have a chat with Sergio and let you know!

**Comment by dehenne** [comment]
Any news here yet? :smile:

**Comment by spekulatius** [comment]
oh, I forgot to update this. I've had a brief chat with Sergio. He said none besides what is in the "next". I didn't check the link in next. I assume its an offset for pagination

**Comment by dehenne** [comment]
eh, that means `https://api.getmakerlog.com/search/tasks/?q=productsync&next=2` is possible? I'll check it out :wink:

**Comment by spekulatius** [comment]
I guess so 👍️

**Comment by dehenne** [comment]
I think you'll like that:

https://github.com/pcsg/pcsg-makerlog-php-client/blob/master/docs/tasks.md#tasks-search

**Comment by spekulatius** [comment]
Hey Henning,

that's awesome. It does literally everything I could ask for. I'll give it a spin asap!

Peter

**Comment by spekulatius** [comment]
Hey Henning,

that's awesome. It does literally everything I could ask for. Thank you! I'll give it a spin asap!

Peter
